### PR TITLE
View holder pattern

### PR DESCRIPTION
**Pull request by manjunathc23**
@manijshrestha  : came up with this idea to have the base class to take the view holder pattern. 
Looks cool to me as well. 

Please let me know your feedback. 

cc : @cdflynn , @manijshrestha 

Thanks!
Manju

### CODE REVIEW

**Comment by manijshrestha** [comment]
Thanks @manjunathc23 for creating this PR from my patch file. This will make the framework strongly opinionated. Thus, wanted to have a larger discussion before having it in the project.

**Comment by manjunathc23** [comment]
@cdflynn & @yeshbourne : Your thoughts?

**Comment by cdflynn** [comment]
This is just me, but I'd lean towards the non-parameterized pattern we're used to for a couple reasons.  
- Non-enforced `mViews` leaves it open to the user to decide on their pattern of choice, but they can still enjoy the other base-class features.  They might be used to some other pattern with `butterknife` etc
- The readme can include a blurb about why `mViews` is great, whout introducing some extra learning curve of abstract base class methods.  The more we can stick to the methods and interfaces they already know (ie, Android calls), the better chance we have of early adoption.

**Comment by manijshrestha** [comment]
I am closing this PR as we wont be going this path.

**Pull request closed without merging**
