### PR TITLE
package structure

### PR DESCRIPTION
**Pull request by cdflynn**
(commit lines)

```
Moved lots of things into top-level packages that might be more recognizable to a large audience.  There is a package for dependency injection, as well as one for view layer classes like activities and fragments.
```

Pull this into your IDE and have a look.  My intention here is to have those top-level packages be familiar enough without losing the clean separation of concerns.

The only other thing I'd add to this is a clear `domain` package, but since `zeta` itself doesn't have a target domain, it doesn't make sense to add one here.  If I were writing an example repo right now, I'd make sure to point out the addition of a `domain` package with `POJO`s inside it.  I would also make clear where the `network data` (retrofit interfaces, etc) should go, as the stubs here don't really define that.

### CODE REVIEW

**Comment by cdflynn** [comment]
Not quite sure what I broke about the CI, as it's building locally.  This break for you guys locally?

**Comment by manjunathc23** [comment]
Hey @cdflynn , 

I see what you have explained to me on the other day.

I like the `di` package structure here. It make sense to have all dependencies injection related at one place. 

Observations : 
1. Fragments and Activities are inside `views` technically they are not views but may contain views. 
2. Looks like the packages have not changed all the way `debug`, `release` and `automation` build variants. 

Question:
1. Where the `@Submodule` would go for the fragment level in this package structure?  

@manijshrestha  : your opinion about this? change.  

Thanks!
Manju

**Comment by manjunathc23** [comment]
Rebase to latest `master` should fix the build error in here.

**Comment by manijshrestha** [comment]
@cdflynn, @manjunathc23, I like the changes here. Stuff looked more organized. To Manju's point, may be we create `ui` package and have Activities and Fragments there? a package named`view` would be inside it for custom views.

Regarding `di` package, at high level it is a good home for it. To Manju's point, based on how things get organized, some sub modules and subcomponents may need to live closer to its "domain". I would think that it will be taken care by when it gets used. 

Regarding the build failure, it is because `AS` didn't refactor the packages in different build variant. 😢 . It only applied it to `freeAutomation` variant.

Thats it from me.

**Comment by cdflynn** [comment]
Thanks @manjunathc23 and @manijshrestha, I'll have a chance to make those updates soon!

**Comment by cdflynn** [comment]
I found places where `master` has written andr**io**d instead of android.

**Comment by manjunathc23** [comment]
@cdflynn , Is this branch ready to merge ?

**Comment by cdflynn** [comment]
@manjunathc23 I think it's in a good spot.  I have spent a few work days out of the last week starting an app from this base - and I already have some tweaks I'd love to talk about before putting any more on a PR.

**Pull request merged**
